runtime: nodejs14  # or the version you're using

handlers:
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
